export interface WeatherInfo {
  code: number;
  label: string;
  description: string;
  iconName: string; // Used to pick icon dynamically in component
  category: 'clear' | 'cloudy' | 'fog' | 'drizzle' | 'rain' | 'snow' | 'thunderstorm';
  themeClass: string; // Tailwind gradient/bg class for weather cards
}

export const WMO_WEATHER_CODES: Record<number, WeatherInfo> = {
  0: {
    code: 0,
    label: 'Clear Sky',
    description: 'Completely clear sky with abundant sunshine',
    iconName: 'Sun',
    category: 'clear',
    themeClass: 'from-amber-500/20 via-orange-400/10 to-blue-500/10 border-amber-500/30 text-amber-600 dark:text-amber-400',
  },
  1: {
    code: 1,
    label: 'Mainly Clear',
    description: 'Mostly clear with minor scattered cloudiness',
    iconName: 'SunMedium',
    category: 'clear',
    themeClass: 'from-amber-400/20 via-sky-400/10 to-indigo-500/10 border-sky-400/30 text-sky-600 dark:text-sky-300',
  },
  2: {
    code: 2,
    label: 'Partly Cloudy',
    description: 'Scattered clouds with periodic sun intervals',
    iconName: 'CloudSun',
    category: 'cloudy',
    themeClass: 'from-sky-500/20 via-slate-400/10 to-blue-600/10 border-sky-500/30 text-sky-700 dark:text-sky-300',
  },
  3: {
    code: 3,
    label: 'Overcast',
    description: 'Dense cloud cover blocking direct sunlight',
    iconName: 'Cloud',
    category: 'cloudy',
    themeClass: 'from-slate-500/20 via-gray-400/10 to-slate-700/10 border-slate-500/30 text-slate-700 dark:text-slate-300',
  },
  45: {
    code: 45,
    label: 'Foggy',
    description: 'Thick ground fog reducing visibility',
    iconName: 'CloudFog',
    category: 'fog',
    themeClass: 'from-slate-400/20 via-zinc-400/10 to-slate-600/10 border-slate-400/30 text-slate-600 dark:text-slate-300',
  },
  48: {
    code: 48,
    label: 'Rime Fog',
    description: 'Freezing fog depositing delicate ice crystals',
    iconName: 'CloudFog',
    category: 'fog',
    themeClass: 'from-cyan-500/20 via-slate-400/10 to-blue-600/10 border-cyan-500/30 text-cyan-700 dark:text-cyan-300',
  },
  51: {
    code: 51,
    label: 'Light Drizzle',
    description: 'Fine, gentle mist drizzle',
    iconName: 'CloudDrizzle',
    category: 'drizzle',
    themeClass: 'from-sky-400/20 via-blue-400/10 to-slate-500/10 border-sky-400/30 text-sky-600 dark:text-sky-300',
  },
  53: {
    code: 53,
    label: 'Moderate Drizzle',
    description: 'Steady light drizzle precipitation',
    iconName: 'CloudDrizzle',
    category: 'drizzle',
    themeClass: 'from-blue-500/20 via-sky-500/10 to-slate-600/10 border-blue-500/30 text-blue-600 dark:text-blue-300',
  },
  55: {
    code: 55,
    label: 'Dense Drizzle',
    description: 'Heavy drizzle with reduced visibility',
    iconName: 'CloudDrizzle',
    category: 'drizzle',
    themeClass: 'from-blue-600/20 via-slate-500/10 to-indigo-600/10 border-blue-600/30 text-blue-700 dark:text-blue-300',
  },
  56: {
    code: 56,
    label: 'Freezing Drizzle',
    description: 'Light freezing drizzle causing slippery icy patches',
    iconName: 'CloudSnow',
    category: 'drizzle',
    themeClass: 'from-cyan-400/20 via-blue-500/10 to-slate-600/10 border-cyan-400/30 text-cyan-600 dark:text-cyan-300',
  },
  57: {
    code: 57,
    label: 'Heavy Freezing Drizzle',
    description: 'Dense freezing drizzle freezing on impact',
    iconName: 'CloudSnow',
    category: 'drizzle',
    themeClass: 'from-cyan-600/20 via-indigo-500/10 to-slate-700/10 border-cyan-600/30 text-cyan-700 dark:text-cyan-200',
  },
  61: {
    code: 61,
    label: 'Slight Rain',
    description: 'Light rain showers',
    iconName: 'CloudRain',
    category: 'rain',
    themeClass: 'from-blue-500/20 via-sky-500/10 to-indigo-600/10 border-blue-500/30 text-blue-600 dark:text-blue-300',
  },
  63: {
    code: 63,
    label: 'Moderate Rain',
    description: 'Continuous moderate rainfall',
    iconName: 'CloudRain',
    category: 'rain',
    themeClass: 'from-blue-600/20 via-indigo-500/10 to-slate-700/10 border-blue-600/30 text-blue-700 dark:text-blue-300',
  },
  65: {
    code: 65,
    label: 'Heavy Rain',
    description: 'Heavy downpour with high accumulation',
    iconName: 'CloudRainWind',
    category: 'rain',
    themeClass: 'from-blue-700/25 via-indigo-600/15 to-slate-800/20 border-blue-700/40 text-blue-800 dark:text-blue-200',
  },
  66: {
    code: 66,
    label: 'Light Freezing Rain',
    description: 'Freezing rain creating black ice hazards',
    iconName: 'CloudSnow',
    category: 'rain',
    themeClass: 'from-cyan-500/20 via-blue-600/10 to-slate-700/10 border-cyan-500/30 text-cyan-600 dark:text-cyan-200',
  },
  67: {
    code: 67,
    label: 'Heavy Freezing Rain',
    description: 'Hazardous heavy freezing rain',
    iconName: 'CloudSnow',
    category: 'rain',
    themeClass: 'from-cyan-700/25 via-blue-800/15 to-slate-900/20 border-cyan-700/40 text-cyan-700 dark:text-cyan-100',
  },
  71: {
    code: 71,
    label: 'Slight Snow',
    description: 'Light snowfall flakes',
    iconName: 'Snowflake',
    category: 'snow',
    themeClass: 'from-sky-300/25 via-indigo-300/15 to-slate-400/10 border-sky-300/40 text-sky-700 dark:text-sky-200',
  },
  73: {
    code: 73,
    label: 'Moderate Snow',
    description: 'Steady snowfall accumulating on surfaces',
    iconName: 'Snowflake',
    category: 'snow',
    themeClass: 'from-blue-300/25 via-cyan-300/15 to-slate-500/10 border-blue-300/40 text-sky-800 dark:text-sky-100',
  },
  75: {
    code: 75,
    label: 'Heavy Snow',
    description: 'Heavy snowstorm with significant accumulation',
    iconName: 'Snowflake',
    category: 'snow',
    themeClass: 'from-blue-400/30 via-slate-300/20 to-indigo-600/20 border-blue-400/50 text-indigo-900 dark:text-sky-100',
  },
  77: {
    code: 77,
    label: 'Snow Grains',
    description: 'Small frozen ice grains falling',
    iconName: 'Snowflake',
    category: 'snow',
    themeClass: 'from-slate-300/20 via-sky-300/10 to-blue-400/10 border-slate-300/30 text-slate-700 dark:text-sky-200',
  },
  80: {
    code: 80,
    label: 'Light Rain Showers',
    description: 'Passing light rain showers',
    iconName: 'CloudRain',
    category: 'rain',
    themeClass: 'from-sky-500/20 via-blue-400/10 to-indigo-500/10 border-sky-500/30 text-sky-700 dark:text-sky-300',
  },
  81: {
    code: 81,
    label: 'Moderate Rain Showers',
    description: 'Intermittent moderate showers',
    iconName: 'CloudRain',
    category: 'rain',
    themeClass: 'from-blue-600/20 via-indigo-500/10 to-slate-600/10 border-blue-600/30 text-blue-700 dark:text-blue-300',
  },
  82: {
    code: 82,
    label: 'Torrential Rain Showers',
    description: 'Heavy, violent rain downpours',
    iconName: 'CloudRainWind',
    category: 'rain',
    themeClass: 'from-indigo-700/25 via-blue-800/15 to-slate-900/20 border-indigo-700/40 text-indigo-800 dark:text-indigo-200',
  },
  85: {
    code: 85,
    label: 'Light Snow Showers',
    description: 'Brief passing snow showers',
    iconName: 'CloudSnow',
    category: 'snow',
    themeClass: 'from-sky-300/20 via-blue-300/10 to-slate-500/10 border-sky-300/30 text-sky-700 dark:text-sky-200',
  },
  86: {
    code: 86,
    label: 'Heavy Snow Showers',
    description: 'Intense snow squalls',
    iconName: 'CloudSnow',
    category: 'snow',
    themeClass: 'from-blue-400/25 via-indigo-400/15 to-slate-600/20 border-blue-400/40 text-indigo-800 dark:text-sky-100',
  },
  95: {
    code: 95,
    label: 'Thunderstorm',
    description: 'Thunderstorm with lightning strikes and rain',
    iconName: 'CloudLightning',
    category: 'thunderstorm',
    themeClass: 'from-purple-600/25 via-indigo-600/15 to-amber-500/10 border-purple-500/40 text-purple-800 dark:text-purple-300',
  },
  96: {
    code: 96,
    label: 'Thunderstorm & Light Hail',
    description: 'Thunderstorm accompanied by small hail',
    iconName: 'CloudLightning',
    category: 'thunderstorm',
    themeClass: 'from-purple-700/25 via-slate-700/15 to-amber-600/10 border-purple-600/40 text-purple-900 dark:text-purple-200',
  },
  99: {
    code: 99,
    label: 'Severe Thunderstorm & Hail',
    description: 'Severe thunderstorm with heavy hail and high winds',
    iconName: 'CloudLightning',
    category: 'thunderstorm',
    themeClass: 'from-amber-600/25 via-purple-800/20 to-slate-900/25 border-amber-600/50 text-amber-900 dark:text-amber-300',
  },
};

export function getWeatherInfo(code: number): WeatherInfo {
  return WMO_WEATHER_CODES[code] || {
    code,
    label: 'Unknown Condition',
    description: 'Weather condition information unavailable',
    iconName: 'Cloud',
    category: 'cloudy',
    themeClass: 'from-gray-500/20 via-slate-400/10 to-gray-600/10 border-gray-400/30 text-gray-700 dark:text-gray-300',
  };
}
